import { useNavigate } from "react-router-dom";
import Logo from "../components/Logo";

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="legal-page">
      <nav className="legal-nav">
        <div className="nav-left" onClick={() => navigate("/")} style={{ cursor: "pointer" }}>
          <Logo size={26} />
          <span className="nav-brand">Research Agent</span>
        </div>
      </nav>

      <article className="legal-content">
        <h1>Terms of Service</h1>
        <p className="legal-updated">Last updated: June 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using Research Agent ("the Service"), you agree to be
          bound by these Terms of Service. If you do not agree, do not use the
          Service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          Research Agent is an AI-powered research tool that uses multiple
          autonomous agents to search the web, synthesize information, and
          generate research reports. The Service is provided "as is" for
          informational and educational purposes.
        </p>

        <h2>3. User Accounts</h2>
        <p>
          You are responsible for maintaining the confidentiality of your account
          credentials. You agree to provide accurate information when creating an
          account and to notify us of any unauthorized use.
        </p>

        <h2>4. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any illegal or unauthorized purpose</li>
          <li>Attempt to gain unauthorized access to the Service's systems</li>
          <li>Submit queries designed to generate harmful, misleading, or defamatory content</li>
          <li>Redistribute generated reports as your own original research without disclosure</li>
          <li>Overload the Service with automated or excessive requests</li>
        </ul>

        <h2>5. AI-Generated Content</h2>
        <p>
          Reports generated by this Service are produced by AI language models
          and may contain inaccuracies, outdated information, or errors. You are
          responsible for verifying any information before relying on it. The
          Service does not guarantee the accuracy, completeness, or reliability
          of any generated content.
        </p>

        <h2>6. Intellectual Property</h2>
        <p>
          You retain ownership of your queries. Generated reports may be used
          freely, but we recommend citing "AI-generated via Research Agent" when
          using them in academic or professional contexts.
        </p>

        <h2>7. Limitation of Liability</h2>
        <p>
          The Service is provided without warranties of any kind. In no event
          shall the developers be liable for any damages arising from the use of
          the Service, including but not limited to reliance on AI-generated
          content.
        </p>

        <h2>8. Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. Continued use
          of the Service after changes constitutes acceptance of the new terms.
        </p>

        <h2>9. Contact</h2>
        <p>
          For questions about these Terms, contact us at{" "}
          <a href="mailto:kpiyush0404@gmail.com">kpiyush0404@gmail.com</a>.
        </p>
      </article>
    </div>
  );
}